### ISSUE TITLE
Tiny Tiny RSS Support

### ISSUE THREAD

**Issue by wangxu94** [shgysk8zer0/awesome-rss#100]
I've been using Firefox's built in feed handling to subscribe to feeds on my Tiny Tiny RSS server. This feature is now being deprecated so it would be great if this gap could be filled.

The subscription path is 

    http://<server>/tt-rss/public.php?op=subscribe&feed_url=<feed url>

This will send the feed url to the Tiny Tiny RSS WebUI, and everything else (authentication, subscription options etc.) will be handled by that.

**Comment by wangxu94** [comment]
Can confirm that v1.3.1 works with Tiny Tiny RSS. Thanks for your work!

`/tt-rss/` was there because I have it running on a non-root directory. My bad.

**Comment by shgysk8zer0** [comment]
I'll have to update it, and you'll have to append that to the root URL.

**Comment by wangxu94** [comment]
Got it, sorry about that. Just so you know, I've tested it both with and without `/tt-rss/` appended to the root URL and it works either way. In fact, it works even if I append the wrong directory to the root URL.

**Comment by shgysk8zer0** [comment]
Fixed in latest release.

Note that you will have to set the URL to `http://<server>/tt-rss/`, including the trailing "/".

**Comment by wangxu94** [comment]
v1.3.2 works as intended. Thanks again.
