### ISSUE TITLE
FreshRSS Support

### ISSUE THREAD

**Issue by mirfire** [shgysk8zer0/awesome-rss#110]
Seeing that you are supporting various feed aggregators like TT-RSS, would it be possible to add support for FreshRSS ?

It works exactly the same as [TT-RSS](https://github.com/shgysk8zer0/awesome-rss/issues/100), but with a different address, obviously. Here are a two examples, [as detailed on the official documentation](https://freshrss.github.io/FreshRSS/en/users/04_Subscriptions.html#firefox-subscription-service):

```
https://example.com/FreshRss/i/?c=feed&a=add&url_rss=<feed_url>
https://rss.example.com/i/?c=feed&a=add&url_rss=<feed_url>
```

The second one isn't in the documentation, but that is how I'm running my own instance, and it works.

You'll also need an icon, and you can find one on the [main repository](https://github.com/FreshRSS/FreshRSS/tree/master/docs/img).

There, thanks in advance !

**Comment by msrn** [comment]
I support this. Currently using this bookmarklet as a workaround

`javascript:(function(){var%20url%20=%20location.href;var%20otherWindow=window.open('about:blank','_blank');otherWindow.opener=null;otherWindow.location='https://domain.com/rss/p/i?c=feed&a=add&url_rss='+encodeURIComponent(url);})();`
