### ISSUE TITLE
FF 64 missing mime type - prompts to download

### ISSUE THREAD

**Issue by atomGit** [shgysk8zer0/awesome-rss#121]
since FF v64, when i click the feed icon in the addy bar, FF immediately prompts to open/download the feed with an external app instead of displaying the feed - this is with the RSS preference set in Awesome RSS

this can be tested right here on GitHub

desktop/laptop
Manjaro Linux
FF v64
Awesome RSS 1.3.5

**Comment by shgysk8zer0** [comment]
Yeah, this is purely due to Firefox removing it's own RSS support, so it's opening it as a file now.

I'm working on the next major version that will deal with this, but it's a pretty substantial addition and I don't have as much time as I'd like to dedicate to this to have it done quickly.
