### ISSUE TITLE
displays  xml contents

### ISSUE THREAD

**Issue by promeneur** [shgysk8zer0/awesome-rss#125]
Awesome rss 1.3.5

**To Reproduce**
1. Go to www.lemonde.fr
2. Click on rss icon
this open a web page displaying contents of https://www.lemonde.fr/rss/une.xml

**Expected behavior**
open a window, asking if I want to use "akregator"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] openSuse leap 15.0 
 - Browser [e.g. chrome, safari] FF 64.0

**Comment by shgysk8zer0** [comment]
The file in question is served with a `Content-Type: text/xml` header. Firefox handles XML and correctly displays the contents.

This is the correct behavior, based on the content-type header. Please report to the site that they are serving feeds with the wrong content-type.
