### ISSUE TITLE
this extension may need update with new codes

### ISSUE THREAD

**Issue by mlgexyz** [shgysk8zer0/awesome-rss#130]
the version 1.3.5 do not have the support for FreshRSS, but I see the support in your codes. Can you compile a new version and update it in firefox add-ons? tkx.

**Comment by wangxu94** [comment]
I don't want to step on anyone's toes here, but I've built a new version based on the current git branch, just for my own use. I'd be happy to attach it here if anyone would like that. Icons don't appear because I'm too dumb to figure that out, but other than that it works fine.

**Comment by Park0** [comment]
@wangxu94 do you have a signed version?

**Comment by wangxu94** [comment]
@Park0 Yup, I've uploaded it [here](https://drive.google.com/open?id=1pgA15CLB4lJREHzPGog7EhjsylEDrWL5).

**Comment by Park0** [comment]
I think u have to use npm & submodules to get the intended result for the icons. 
```
npm install 
npm build
```
Maybe we can make a beta version for this plugin so anyone can use it, place pull requests. Ill look into building one if i get my other project fixed :)

**Comment by wangxu94** [comment]
Thanks for the tip. That did work, and I was able to install the resulting .zip file in Firefox dev edition with icons showing up and everything. However, when I try to make a signed version, I get this error:

```
web-ext sign --api-key=XXX --api-secret=YYY
Applying config file: ./package.json
Building web extension from /home/wangxu/awesome-rss
Validating add-on [.......................................................................................................................................................................................]
Validation results: https://addons.mozilla.org/en-US/developers/upload/ce31b424e74c437da7bb8eeae5979d9a
Your add-on failed validation and could not be signed
FAIL

o: The extension could not be signed
    at /usr/local/lib/node_modules/web-ext/dist/webpack:/src/cmd/sign.js:141:15
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
[Link to the verification results](https://addons.mozilla.org/en-US/developers/upload/ce31b424e74c437da7bb8eeae5979d9a)

It looks like there are some syntax errors in the files from the octicons repository. Unfortunately I can't troubleshoot that as I don't know javascript. Any ideas?

**Comment by Park0** [comment]
@wangxu94 If u are interested i just uploaded a signed xpi see #136

**Comment by wangxu94** [comment]
@Park0 That's great, thank you!
