### ISSUE TITLE
Subscribe using: Nextcloud URL issue

### ISSUE THREAD

**Issue by ajh0912** [shgysk8zer0/awesome-rss#137]
### Steps to reproduce

1. Go to Add-Ons > Awesome RSS > Options > Choose 'Subscribe using: NextCloud', enter your Nextcloud server FQDN
2.  Go to a website, click the Awesome RSS icon
3.  You will be taken to https://YOUR-FQDN/apps/news/?subscribe_to=FEED-URL

### Expected behavior
Opens Nextcloud News with the subscribe 'Web address' option prefilled with FEED-URL

### Actual behavior
403 Forbidden
Forbidden
You don't have permission to access this resource.

### Proposed fix
Looks like the URL format should be https://YOUR-FQDN/index.php/apps/news/?subscribe_to=FEED-URL

Nextcloud 18.0.1
News 14.1.3

**Comment by Pingger** [comment]
No, the given nextcloud instance is configured incorrectly.

IF you are the owner, you should make sure that (for apache2; if you are using nginx you would need look for the equivalent there)
- mod_rewrite is enabled
- nextcloud can write to .htaccess
- apache2 is configured to actually use the .htaccess

The .htacess should contain a section like this, if it does and it is not working, your server ignores the file or does not have mod_rewrite enabled:
```
<IfModule mod_rewrite.c>
  Options -MultiViews
  RewriteRule ^core/js/oc.js$ index.php [PT,E=PATH_INFO:$1]
  RewriteRule ^core/preview.png$ index.php [PT,E=PATH_INFO:$1]
  RewriteCond %{REQUEST_FILENAME} !\.(css|js|svg|gif|png|html|ttf|woff2?|ico|jpg|jpeg|map|webm|mp4)$
  RewriteCond %{REQUEST_FILENAME} !core/img/favicon.ico$
  RewriteCond %{REQUEST_FILENAME} !core/img/manifest.json$
  RewriteCond %{REQUEST_FILENAME} !/remote.php
  RewriteCond %{REQUEST_FILENAME} !/public.php
  RewriteCond %{REQUEST_FILENAME} !/cron.php
  RewriteCond %{REQUEST_FILENAME} !/core/ajax/update.php
  RewriteCond %{REQUEST_FILENAME} !/status.php
  RewriteCond %{REQUEST_FILENAME} !/ocs/v1.php
  RewriteCond %{REQUEST_FILENAME} !/ocs/v2.php
  RewriteCond %{REQUEST_FILENAME} !/robots.txt
  RewriteCond %{REQUEST_FILENAME} !/updater/
  RewriteCond %{REQUEST_FILENAME} !/ocs-provider/
  RewriteCond %{REQUEST_FILENAME} !/ocm-provider/
  RewriteCond %{REQUEST_URI} !^/\.well-known/(acme-challenge|pki-validation)/.*
  RewriteRule . index.php [PT,E=PATH_INFO:$1]
  RewriteBase /
  <IfModule mod_env.c>
    SetEnv front_controller_active true
    <IfModule mod_dir.c>
      DirectorySlash off
    </IfModule>
  </IfModule>
</IfModule>
```

**Comment by hydrian** [comment]
Check the following situations:

 * Do you have the NextCloud News app installed and enabled? 
 * Are you already logged into your NextCloud instance? 
 * Does the user you are logged in with have access to the News app?

**Comment by ajh0912** [comment]
Aplogies for the delay, @Pingger was correct - the instance was misconfigured
