### ISSUE TITLE
TinyTinyRSS has changed the subscribe link

### ISSUE THREAD

**Issue by nebulade** [shgysk8zer0/awesome-rss#151]
I am not exactly sure since which version, since it has moved to a rolling release cycle, but the TinyTinyRSS subscribe URL schema has changed slightly. I am testing this on the Cloudron TTRss package for it which comes as git sha 9669bb94de

The URL created currently by this plugin is https://example.com/public.php?op=subscribe&feed_url=https://somefeedurl, however the `op` is now `bookmarklets--subscribe` instead of `subscribe`

**Comment by solarchemist** [comment]
Can confirm this. I recently upgraded my TinyTinyRSS, and now the subscribe functionality is broken, but fixable by manually changing the URL as described by @nebulade.

The change occurred sometime between commit `05744bb474e55c4f85acd236dd2883679c278e70`(Sep 22, 2020) and commit `079f6dfdd0a26e9ba68aff6f05072d1720f6a6af` (Feb 5, 2022) (which is not very helpful, I know :-)

In any case, can we fix this without breaking the functionality for either old or recent TTRSS installs? Or should awesome-rss only aim to support the current API?

And while others ponder that, does anyone know how to patch awesome-rss locally to adjust the URL?

**Comment by solarchemist** [comment]
Seems this issue is a duplicate of #144. Sorry about not noticing before posting.

For any newcomers, I suggest all discussion on this issue be kept over there. For the OP or @shgysk8zer0, please consider closing this issue in favour of #144?

**Comment by nebulade** [comment]
closing this in favor of #144
