### ISSUE TITLE
Delay scanning tabs until active

### ISSUE THREAD

**Issue by shgysk8zer0** [shgysk8zer0/awesome-rss#21]
### Steps to reproduce
1.  Install or update add-on. Or just start browser

### Expected behavior
Tabs should be queued and wait until active to scan

### Actual behavior
All tabs are scanned immediately

### Screenshots and/or logs (see how to open the developer console in your browser)
Drag and drop file to upload and include in bug report

**Comment by MikkCZ** [comment]
Well, maybe scanning for active tabs will be good enough. If I understand the tab status correctly, not active tab is not loaded at all. Once the tab becomes active, it should load and trigger the content script the same way as for new tabs.
