### ISSUE TITLE
Dark theme icon color

### ISSUE THREAD

**Issue by Keith94** [shgysk8zer0/awesome-rss#24]
STR: 
1. Enable the dark theme in Firefox
2. Hover the rss icon in the awesome bar

Actual results:

Icon is nearly invisible because the background is the same color when hovering. Maybe the icon should be lighter to match the native rss icon?
![2017-09-21_16-33-23](https://user-images.githubusercontent.com/5490615/30723217-a3f44064-9eea-11e7-84bc-4d602862aed3.gif)

**Comment by shgysk8zer0** [comment]
I've been trying to figure this one out for a while now and, from what I can tell, I'm waiting for Firefox to implement this functionality for page action add-ons. There is an [open bug for Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1398156)

I am using the [native rss icon ![](http://design.firefox.com/icons/icons/places/subscribe-16.svg)](http://design.firefox.com/icons/viewer/#subscribe) , but cannot distinguish between light/dark themes. Using `fill="context-fill"` leaves the icon black, which is even worse.

There is no [JavaScript API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API) to get light/dark theme to change icon accordingly, and no [manifest key](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json) to give alternate icon for light/dark themes.

**Comment by Keith94** [comment]
So it can't be fixed for now, that's good to know :) Thanks for the reply

**Comment by shgysk8zer0** [comment]
As a user of the dark theme myself, believe me that I'm looking forward to this being possible. I was very tempted to use the icon for the dark theme by default, but decided to use the light theme icon under the assumption that was the better choice for more people.

**Comment by shgysk8zer0** [comment]
I'm working on an options page that will allow manually selecting icons. It won't happen automatically, but you can select the icon that fits your theme & preferences.

**Comment by Keith94** [comment]
Good idea, I'm liking the new orange icon a lot too. Thanks!

**Comment by MikkCZ** [comment]
@shgysk8zer0 FYI, it would be a dirty hack and need extra persmission, but using [`management.getAll()`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/management/getAll) you could determine, which one from the built-in themes is active, and set the icon automatically based on this information.

**Comment by shgysk8zer0** [comment]
Finally, there is [`browser.theme.getCurrent()`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/theme/getCurrent)]. It's not available until 58, but this is the way to do it without unnecessary permissions.
