### ISSUE TITLE
Button doesn't load when navigating on GitHub

### ISSUE THREAD

**Issue by Keith94** [shgysk8zer0/awesome-rss#25]
It may be a bug or limitation in the WebExtensions API, but I wanted to report it just in case. ;)

### Steps to reproduce
1.  Navigate to https://github.com/shgysk8zer0/awesome-rss/issues
2.  Click on one of the other tabs (e.g. Pull requests)

### Expected behavior
RSS icon should(?) re-appear or stay visible in the url bar

### Actual behavior
RSS icon disappears from url bar and requires reloading the page to appear again

**Comment by shgysk8zer0** [comment]
Confirmed. It also suffers from the same issue when navigating using the back/forward buttons.
In the case of the reported issue, the problem seems to be that the `DOMContentLoaded` event isn't triggered on `fetch`/`XHR`.
