### ISSUE TITLE
(Suggestion) No bold font

### ISSUE THREAD

**Issue by happysurf** [shgysk8zer0/awesome-rss#27]
In my opinion when the font size is small the bold don't increase the legibility.
In addition appear too strong and not consistence with the Firefox UI text.
The text must be the same of Page Action menu, much clear to see.. 

![rss](https://user-images.githubusercontent.com/13637587/30752083-7d445914-9fbb-11e7-8a0b-e58b08bafe3a.png)
![rss2](https://user-images.githubusercontent.com/13637587/30752422-8e156782-9fbc-11e7-9a46-6c9951a84478.png)

**Comment by shgysk8zer0** [comment]
I see your point.
Typically, titles are aesthetically distinct from commands and given an `<h1>` tag, but that can decrease legibility.
