### ISSUE TITLE
Autosave preferences

### ISSUE THREAD

**Issue by MikkCZ** [shgysk8zer0/awesome-rss#39]
When the preferences are changed, they should be saved automatically, without the need of clicking any save button. Feel free to use my [`options-ui.js`](https://github.com/MikkCZ/pontoon-tools/blob/master/src/js/options-ui.js) as an inspiration, how to do that e.g. with a `change` event listener.

**Comment by shgysk8zer0** [comment]
On a related note, I am **really** looking forward to module support being enabled by default.
