### ISSUE TITLE
Chrome support?

### ISSUE THREAD

**Issue by shgysk8zer0** [shgysk8zer0/awesome-rss#4]
Tues should be mostly compatible, with the following exceptions:
- Chrome does not natively support RSS
- Chrome does not support SVG icons
- Not sure if I can get icon in URL bar

**Comment by MikkCZ** [comment]
Chrome has many add-on, that support RSS feed from discovery to subscription via various services. Thus I wouldn't target Chrome with such easy add-on (and won't complicate it for Firefox users just because of Chrome).

**Comment by shgysk8zer0** [comment]
The simplicity of the add-on is exactly why I wanted this to be a Chrome extension as well. Better to work out compatibility with something like this.

Good point about the extensions available on Chrome though. It's reasonable to assume that any extension capable of handling RSS & Atom feeds will already be providing this functionality.
