### ISSUE TITLE
[Feature Request] Feed aggregation

### ISSUE THREAD

**Issue by LoveIsGrief** [shgysk8zer0/awesome-rss#60]
Hi,

This might be a big feature request and possible suited for a separate extension, but here goes anyway. Since you have access to the bookmarked feeds, a page to view the bookmarks and possibly aggregate all RSS entries in one big list would be great.

I just haven't been able to find a **local** RSS feed aggregator without the need to give out my email and be tracked.

If this is out of scope, I'll be happy to develop a new extension myself.

Cheers and thanks for the existing plugin 👍

**Comment by dos1** [comment]
Just an out-of-topic suggestion: try CommaFeed. I'm using it self-hosted on my own server and I'm happy with it :)

**Comment by shgysk8zer0** [comment]
@LoveIsGrief 
I've considered implementing this feature, and do not believe that it would be best implemented in this add-on. If you find anything that provides this, I would be happy to add a recommendation in my description.

The reason for this is that there are at least a few great solutions already available, and having the freedom to view your subscriptions in any number of clients is one of my favorite things about RSS
- Firefox's Live Bookmarks
- [FeedReader](https://jangernert.github.io/FeedReader/) *Linux only*
- [QuiteRSS](https://quiterss.org/)
- [Feedly](https://feedly.com/)
- Countless others

I think that this would be a great candidate for a PWA. Specifically, it would be really interesting to see a web-based feed reader with offline access that stores feeds in `IndexedDB`, and therefore does not require creating an account. Could sync in background and create notifications using service workers (not sure of support for background `fetch`ing). Can't forget [`navigator.registerContentHandler`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerContentHandler)

I also do not have access to bookmarked feeds. I'm pretty sure I'd need bookmarks permission for that.

**Comment by LoveIsGrief** [comment]
@dos1 Thanks for the suggestion. It's not quite what I'm looking for. I'm quite adverse to self-hosted solutions, that do not provide more functionality than a possible single addon in a browser.  
Weird actually, that I'd spend more time and resources writing an addon myself, than self-hosting. Go figure 😋 

@shgysk8zer0 Thanks for the response. I wanted to avoid installing extra software, when I already have firefox open or creating an account and unnecessarily sharing my information with a third party.

I'll give FeedReader a go. Maybe I can settle with it. Otherwise, I'll just write my own addon 😄 

Cheers, y'all
