### ISSUE TITLE
Update Russian messages

### ISSUE THREAD

**Issue by shgysk8zer0** [shgysk8zer0/awesome-rss#72]
Update `_locales/ru/messages.json`.

The full list of messages may be found in [`_locales/en/messages.json`](https://github.com/shgysk8zer0/awesome-rss/blob/master/_locales/en/messages.json)

[![Awesome RSS :: Statistics](https://i.imgur.com/dJlmqqY.png)](https://addons.mozilla.org/en-US/firefox/addon/awesome-rss/statistics/?last=30)

[Awesome RSS](https://addons.mozilla.org/en-US/firefox/addon/awesome-rss/) is about to surpass 5,000 daily users, and I would really like to have the add-on localized for the most common languages so that it's more friendly to the majority of users. I do not trust Google Translate for the job, and am asking users for help with this.

If you are willing to help, it only requires some copy/pasting and working in a JSON file. To see all open issues requesting translations, look through [issues with the translations label](https://github.com/shgysk8zer0/awesome-rss/issues?q=is%3Aissue+is%3Aopen+label%3ATranslations). For all issues requesting help, there is also a ["help wanted" label](https://github.com/shgysk8zer0/awesome-rss/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) and a ["good first issue" label](https://github.com/shgysk8zer0/awesome-rss/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)

Please create/update the appropriate locale, matching the [English version](https://github.com/shgysk8zer0/awesome-rss/blob/master/_locales/en/messages.json), and submit a pull request referencing the issue. Other languages are, of course, always welcome.

**Comment by turisap** [comment]
Hi @shgysk8zer0, I'm currently looking for getting experience in contributing to open-source, and, as a native Russian speaker, would like to try to help you here. Can I do the job? But as a newbie, I would need some explicit instructions)

**Comment by shgysk8zer0** [comment]
@turisap I see that you're made some contributions already, so I assume you are familiar with forking and pull requests.

What you'd need to to is update `_locales/ru/messages.json` to match `_locales/en/messages.json`, updating `*.message`.

[![](https://i.imgur.com/pG49LZal.png)](https://imgur.com/pG49LZa)

If you need any context, everything new will be in the options / preferences page.

[![](https://i.imgur.com/k0QuagYl.png)](https://imgur.com/k0QuagY)

You'll need [NPM](https://nodejs.org/) to run any changes locally. After running `npm install`, you'll be able to run `npm start`, which will open a testing version of Firefox with an empty profile with Awesome RSS installed.

**Comment by shgysk8zer0** [comment]
Resolved in pull request #77
