### ISSUE TITLE
Light theme color is off from other (native) icons in URL bar

### ISSUE THREAD

**Issue by quassy** [shgysk8zer0/awesome-rss#91]
### Steps to reproduce
1. Visit a page that has a rss feed
2. Compare the shade of grey of awesome rss and other native toolbar buttons

### Expected behavior
The subscribe button should look native and have the same shade of grey.

### Actual behavior
The subscribe button for light theme is brighter `#7F7F80` than other buttons like _star_ `#666666` in the URL bar.

I believe there are two different shades of grey depending on whether the icon is shown in the URL bar or in the ellipsis menu.

### Screenshots and/or logs (see how to open the developer console in your browser)
![shadeofgrey](https://user-images.githubusercontent.com/369996/43351666-96996c7c-9215-11e8-9db9-2b423460d57a.PNG)

**Comment by shgysk8zer0** [comment]
@quassy I guess they changed this on me. I'm using the actual [Photon icon](https://design.firefox.com/icons/viewer/#), and I guess I need to do some updates to keep up.
