### ISSUE TITLE
New tab should open popup right next to current tab

### ISSUE THREAD

**Issue by rugk** [shgysk8zer0/awesome-rss#94]
### Steps to reproduce
1.  Open a feed when setting is set to "opne in new tab"

### Expected behavior
Just like "view source" opens to the right of the current tab.

### Actual behavior
Opens at the end of tab list.

### Screenshots and/or logs (see how to open the developer console in your browser)

See https://github.com/april/certainly-something/issues/12 where another add-on had the same problem.

**Comment by happysurf** [comment]
Follow these steps:
- Load about:config and digit the string **browser.tabs.insertAfterCurrent** in the Firefox address bar.
- Confirm that you will be careful if the warning page is displayed.
- Set the preference to true by double-clicking on it.
- Restart the browser.

**Comment by rugk** [comment]
Yes, but this affects all tabs. This is not wwhat I want.

See also the discussion under https://github.com/april/certainly-something/issues/12#issuecomment-407778581:
> I would like it to work like "View Page Source" and open a new tab to the immediate right of the current page

**Comment by shgysk8zer0** [comment]
I'll look into this. I'm not sure if I have any control.

If added, does a preference / checkbox defaulting to checked sound right? Or would it make more sense to add it to the `<option>`s of opening feeds?

**Comment by Keith94** [comment]
Should be possible with the the browserSettings API "newTabPosition"

https://reviewboard.mozilla.org/r/225956/diff/5/

**Comment by rugk** [comment]
Checkbox, but generally I don't need it be configurable- You also cannot configure `View site source`.

> I'm not sure if I have any control.

Yes, you have: https://github.com/april/certainly-something/commit/d8b6f0d40ea8b695f9a399746f91aa64e0496d19

**Comment by rugk** [comment]
@Keith94 No, that should not change the browser settings. :smile: See commit linked above (why do I even link to _solved_ issues already twice…? Two clicks and you see the solution.)

**Comment by shgysk8zer0** [comment]
@rugk Sometime people scan through issues without reading every comment in detail or opening every link. I haven't opened the link myself yet (I'm not in a position right now to go too in depth into anything, but I do have a few minutes), but I expect I'll find instructions on how to control tab position in there somewhere.

**Comment by shgysk8zer0** [comment]
@rugk There's now a "New tab" & "Adjacent tab" option.
