### ISSUE TITLE
"Subscribe Using" layout is confusing

### ISSUE THREAD

**Issue by ssokolow** [shgysk8zer0/awesome-rss#96]
### Steps to reproduce
1.  Open the Awesome RSS options page

### Expected behavior

1. It should be clear which radio button corresponds to which entry without trial and error.
2. The Radio buttons should be to the left of their labels.

  Standard UI convention for as long as I can remember has been to lay out radio buttons and checkboxes as if they were bullet points so, unlike all other form widgets, they go to the left of their labels rather than the right. [GUIdebook confirms](https://guidebookgallery.org/screenshots/macos70/) that as the case in the Appearance control panel of Apple System 7.0, so it's been that way since at least May 1991.

 The Xerox Alto doesn't appear to have checkboxes, so I'm assuming they were an Apple creation, but I wasn't able to find any older screenshots of checkboxes or radio buttons in a horizontal layout. (Though the custom "labels above/below button" layout used in the Mouse control panel traces all the way back to the double-click speed selector in [System 1.1](https://guidebookgallery.org/screenshots/macos11) in 1984, when ratio buttons hadn't even finished taking on their modern form yet.)

### Actual behavior

1. The label+button pairs are so close together than it's unclear what goes with what
2. The radio buttons are to the right of the labels, which further muddles things up.

### Screenshots and/or logs (see how to open the developer console in your browser)
![screenshot12](https://user-images.githubusercontent.com/46915/43668762-90ff51b4-974c-11e8-9a26-eef6cae70c1e.png)

### Desired Screenshot
![screenshot13](https://user-images.githubusercontent.com/46915/43669208-57bb2b14-974f-11e8-847e-d1446cad449c.png)

**NOTE:** In the reworked screenshot, I put the `<input>` element inside the `<label>` element and set all of the elements within the `<label>` to `vertical-align: bottom;` for a more visually-pleasing layout. (It *is* valid to put the control inside the label associated with it.)

**Comment by ssokolow** [comment]
In fact, the rest of the options icons line up much more nicely if you also set
 `form svg.icon { vertical-align: middle; }`

![screenshot16](https://user-images.githubusercontent.com/46915/43669432-f819ee6e-9750-11e8-9902-7970e599729c.png)

**Comment by rugk** [comment]
Hwy not make a PR, if you've already found out how to fix much stuff of it?

**Comment by ssokolow** [comment]
Because making a PR is significantly more involved than using the element-picker button from the "debug" option in `about:debugging`.

For example:

* This was just a simple matter of using the "Select element" button in the DOM inspector and then live-editing some bits and pieces until things look right. A PR would require me to download the repository, identify which file(s) to modify, run a test build of the extension, test it to make sure that I didn't break anything, etc.
* A screenshot doesn't require me to determine what coding conventions the project is using so I can follow them. A PR does.
* A PR would require me to make absolutely sure that the changes I made don't regress things elsewhere in the project. If I'm just taking a quick screenshot, I can be sloppy there.

**Comment by rugk** [comment]
So in other words: You want to confirm that the changes will be accepted, before getting into the 'work' of making a PR.

**Comment by ssokolow** [comment]
Partly that, but it's also a question of mindset. What I posted was a chain of "just one more"s that got carried away, so it was easy to do on my leisure time.

Actually making a PR feels like work, which means it's much harder to justify taking a bite out of my leisure time to do it.

**Comment by rugk** [comment]
It's not as serious as you think… :wink: 

But let's wait what the maintainer says.

**Comment by ssokolow** [comment]
> It's not as serious as you think… :wink:

I'm the only one qualified to say how series issues of mindset are and I say that, especially now when I've accidentally jet-lagged myself, any successes at motivating myself to do something on the same level of formality as a PR are to be directed to my own backlogged projects.
