### ISSUE TITLE
Nextcloud support

### ISSUE THREAD

**Issue by rugk** [shgysk8zer0/awesome-rss#97]
From https://github.com/shgysk8zer0/awesome-rss/issues/95#issuecomment-410382301

Support Nextcloud News: https://github.com/nextcloud/news/

Here is the API doc: https://github.com/nextcloud/news/blob/master/docs/externalapi/External-Api.md

Of course, you need to provide the user the ability to enter their Nextcloud server URl somewhere. (and signup, I guess).

Signup can be done via OAUTH in new Nextcloud versions, or just the password/device-specific password by the user.
But, probably, you don't need to authenticate and just can assume the user is logged in in the browser. Just don't know how that works with WebExtensions.

**Comment by shgysk8zer0** [comment]
@rugk The plan is to have an input for the domain of a Nextcloud / Owncloud instance, check `/status.php` to verify the address and that it's running, and then to use the subscription path (`new URL(instanceURL, subscribePath)`) to open a window / tab.

Have a hidden & disabled input which becomes required if Nextcloud is seleced.
